### ISSUE TITLE
[Crash] Crashing with latest version of Sponge

### ISSUE THREAD

**Issue by itsEvil** [yrsegal/thicc-entities#11]
Crashing with latest version of SpongeForge 1.12.2-2838-7.1.10. Specifically with Mixin as it changes the entityplayer.
aaaa = spongeforge

```
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Transforming EntityPlayer
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Applying Transformation to method (Names [getDefaultEyeHeight, ] Descriptor ()F)
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Attempting to insert: Default eye height
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Patch result: Success
11.03 12:41:36 [Server] main/WARN [mixin]: Error loading class: net/minecraft/entity/player/EntityPlayer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer wiresegal.thicc.asm.ThiccAsmTransformer@935493d from coremod ThiccEntities Plugin)
11.03 12:41:36 [Server] main/ERROR [mixin]: mixins.forge.core.json:entity.player.EntityPlayerMPMixin_Forge: Super class 'org.spongepowered.common.mixin.core.entity.player.EntityPlayerMixin' of entity.player.EntityPlayerMPMixin_Forge was not found in the hierarchy of target class 'net/minecraft/entity/player/EntityPlayerMP'
11.03 12:41:36 [Server] INFO org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Super class 'org.spongepowered.common.mixin.core.entity.player.EntityPlayerMixin' of entity.player.EntityPlayerMPMixin_Forge was not found in the hierarchy of target class 'net/minecraft/entity/player/EntityPlayerMP'
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard.validate(MixinInfo.java:589) ~[aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:325) ~[aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:903) ~[aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:672) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
11.03 12:41:36 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
11.03 12:41:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.Class.forName(Class.java:348) [?:1.8.0_191]
11.03 12:41:36 [Server] INFO at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
11.03 12:41:36 [Server] INFO at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
11.03 12:41:36 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2847-universal.jar:?]
11.03 12:41:36 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2847-universal.jar:?]
11.03 12:41:36 [Server] main/INFO [BetterFps]: Patching math utils with "RIVENS_HALF" algorithm
11.03 12:41:36 [Server] main/INFO [mixin]: A re-entrant transformer 'guichaguri.betterfps.transformers.MathTransformer' was detected and will no longer process meta class data
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Transforming EntityPlayer
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Applying Transformation to method (Names [getDefaultEyeHeight, ] Descriptor ()F)
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Attempting to insert: Default eye height
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Patch result: Success
11.03 12:41:36 [Server] main/WARN [mixin]: Error loading class: net/minecraft/entity/player/EntityPlayer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer wiresegal.thicc.asm.ThiccAsmTransformer@935493d from coremod ThiccEntities Plugin)
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Transforming EntityPlayer
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Applying Transformation to method (Names [getDefaultEyeHeight, ] Descriptor ()F)
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Attempting to insert: Default eye height
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Patch result: Success
11.03 12:41:36 [Server] main/WARN [mixin]: Error loading class: net/minecraft/entity/player/EntityPlayer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer wiresegal.thicc.asm.ThiccAsmTransformer@935493d from coremod ThiccEntities Plugin)
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Transforming EntityPlayer
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Applying Transformation to method (Names [getDefaultEyeHeight, ] Descriptor ()F)
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Attempting to insert: Default eye height
11.03 12:41:36 [Server] main/INFO [Thicc ASM]: Patch result: Success
11.03 12:41:36 [Server] main/WARN [mixin]: Error loading class: net/minecraft/entity/player/EntityPlayer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer wiresegal.thicc.asm.ThiccAsmTransformer@935493d from coremod ThiccEntities Plugin)
11.03 12:41:36 [Server] main/WARN [mixin]: Method overwrite conflict for func_71222_d in mixins.vanillafix.bugs.json:MixinMinecraftServer, previously written by org.spongepowered.common.mixin.core.server.MinecraftServerMixin. Skipping method.
11.03 12:41:36 [Server] main/INFO [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:98]: Added INTERFACE: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
11.03 12:41:36 [Server] main/INFO [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:135]: Added METHOD: net.minecraft.world.World.foamfix_removeUnloadedEntities
11.03 12:41:36 [Server] main/WARN [mixin]: Re-entrance detected, this will cause serious problems.
11.03 12:41:36 [Server] INFO org.spongepowered.asm.mixin.transformer.throwables.ReEntrantTransformerError: Re-entrance error.
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:336) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [aaaa.jar:1.12.2-2838-7.1.10]
11.03 12:41:36 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
11.03 12:41:36 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
11.03 12:41:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.Class.privateGetMethodRecursive(Class.java:3048) [?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.Class.getMethod0(Class.java:3018) [?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.Class.getMethod(Class.java:1784) [?:1.8.0_191]
11.03 12:41:36 [Server] INFO at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.12.jar:?]
11.03 12:41:36 [Server] INFO at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
11.03 12:41:36 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
11.03 12:41:36 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2847-universal.jar:?]
11.03 12:41:36 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2847-universal.jar:?]
11.03 12:41:36 [Server] INFO A problem occurred running the Server launcher.[12:41:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at java.lang.reflect.Method.invoke(Method.java:498)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.getDeclaredMethods0(Native Method)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.getMethod0(Class.java:3018)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.getMethod(Class.java:1784)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
11.03 12:41:36 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: ... 6 more
11.03 12:41:36 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
11.03 12:41:36 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:643]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
11.03 12:41:36 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:643]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
11.03 12:41:36 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:643]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
11.03 12:41:36 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:643]: ... 13 more
11.03 12:41:36 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.ReEntrantTransformerError: Re-entrance error.
11.03 12:41:36 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:667]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:336)
11.03 12:41:36 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:667]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
11.03 12:41:36 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:667]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
```

**Comment by Iomega0318** [comment]
Yep I'm seeing the same thing, considering the code hasn't been updated in 2 years I might just remove this from the modpack I'm using.

**UPDATE**
After removing this the server started up with no issues, I have the logs if you want them but it's the same information as the OP.
